//empty array to store the game sequence.
let gameSeq=[];
//empty to store the user sequence.
let userSeq=[];

//It check wheather game started or not.
let started=false;

//store the level at which user is.
let level=0;
let high=1;
//Accessing the h3 heading.
let h3=document.querySelector('h3');

//To store the class of button so that we can randomly choose from them.
let btns=['one','two','three','four'];

//we apply event listener on our document. so that if user press any key on keyboard
//then the game will  start.
document.addEventListener('keypress',function(){
    //If the game is not started i.e started=false then only it start the game.
    if(started==false){
        console.log("Game started");
        //It signify that the game is started and won't be started until game is over.
        started=true;
        //We call the levelUp function to increase the level from 0 to 1.
        levelUp();
    }
});

//To flash the button by game.
function gameFlash(btn){
    btn.classList.add('flash');
    //we remove the flash class after 1s to appear the button flashed.
    setTimeout(function(){
        btn.classList.remove('flash');
    },250);
}
//To flash the button by user.
function userFlash(btn){
    btn.classList.add('userFlash');
    //we remove the flash class after 1s to appear the button flashed.
    setTimeout(function(){
        btn.classList.remove('userFlash');
    },250);
}

//To level up the game.

function levelUp(){

    //setting the user sequence to empty.so that user will enter the complete sequence.
    userSeq=[];

    level++;//level will be increased by one.
    h3.innerText=`Level: ${level}`;

    //To choose from the colors of button from index 0 to 2
    let randomIndex=Math.floor(Math.random()*4);
    //To choose that random index color.
    let randomClass=btns[randomIndex];
    //to choose the random button.
    let randomBtn=document.querySelector(`.${randomClass}`);
    // console.log(randomIndex);
    // console.log(randomClass);
    // console.log(randomBtn);


    //calling the userFlash to flash any random button by the game.
    gameFlash(randomBtn);
    //adding the random button class which is generated by game.
    gameSeq.push(randomClass);
    

    // //printing the game sequence.
    console.log(gameSeq);
}

//function for button press.
function buttonPress(){
    // console.log(this);
    let btnpress=this;//Here this will act as the button which is pressed by the user.
    //To call the button Flash function to flash the button by the user.
    userFlash(btnpress);

    //to get which button class user has pressed.
    let userClass=btnpress.getAttribute('id');
    // console.log("User pressed button with id:",userClass);
    //push userClass into the user Sequence.
    userSeq.push(userClass);

    //calling the checkCurrLevel function.
    checkCurrLevel(userSeq.length-1);
}




//Checking the current level.
function checkCurrLevel(index){
    // console.log("Current level:",level);
    // console.log(index);
    // console.log(userSeq);    
    // console.log(gameSeq);

    if(userSeq[index]===gameSeq[index]){
        console.log("same value");
        if(userSeq.length==gameSeq.length){
            //adding a delay to level up function.
            setTimeout(levelUp,1000);
        }
    }else{
        h3.innerHTML=`Game over! your score is <b>${level}</b> <br> press any key to start.`;
        document.querySelector('body').style.backgroundColor='red';
        setTimeout(function(){
            document.querySelector('body').style.backgroundColor='white';
        },250);
        let hs=document.querySelector(".high-score-text");
        hs.innerText=`High Score : ${highScore(level)}`;
        resetGame();

    }
}




//Accessing all the button with class btn.
let allBtns=document.querySelectorAll('.btn');
//Looping throught all buttons to apply event listener.
for(b of allBtns){
    b.addEventListener('click',buttonPress);
}

//reset function to reset the game.
function resetGame(){
    started=false;
    userSeq=[];
    gameSeq=[];
    level=0;
}


//function to print highest score.
function highScore(level)
{
    if(level>high)
    {
        high=level;
    }
    return high;
}